#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=38 blur_radius=30 color=0x60000000 shadow.color=0x28000000 shadow.angle=0 \
  border_width=1 border_color=0x28222222 corner_radius=6 margin=8 y_offset=5 padding_left=8 padding_right=8
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.color=0x44444444
  background.padding_right=6 background.height=25 \
  background.corner_radius=6
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("" "" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    background.color=0x888888
    background.corner_radius=5
    background.height=25
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app icon.drawing=on icon.font="sketchybar-app-font:Regular:16.0" script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events
#
sketchybar --add bracket spotify_controls \
  spotify.next spotfy.playpause spotify.back

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \

sketchybar --add event spotify_change com.spotify.client.PlaybackStateChanged
sketchybar --add item spotify center \
  --set spotify \
  background.padding_left=$GAP \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

SPOTIFY_ICON_SIZE=19
SPOTIFY_CONTROL_GAP=0

sketchybar --add item spotify.back center \
  --set spotify.back \
  icon=󰒮 \
  label.padding_left=0 label.padding_right=7 \
  icon.padding_left=8 icon.font.size=$SPOTIFY_ICON_SIZE \
  background.drawing=off \
  background.padding_right=$SPOTIFY_CONTROL_GAP \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.back mouse.clicked

sketchybar --add item spotify.playpause center \
  --set spotify.playpause \
  icon= \
  icon.font.size=15 \
  icon.y_offset=1 icon.padding_left=9 \
  label.padding_left=0 label.padding_right=7 \
  background.drawing=off \
  background.padding_right=$SPOTIFY_CONTROL_GAP \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.playpause mouse.clicked

sketchybar --add item spotify.next center \
  --set spotify.next \
  icon=󰒭 icon.font.size=$SPOTIFY_ICON_SIZE \
  label.padding_left=0 label.padding_right=7 \
  background.drawing=off \
  background.padding_right=0 \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.next mouse.clicked

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
